namespace WritingVaultMcp.Infrastructure.Access;

/// <summary>
/// Cross-table rules that Access foreign keys cannot express. The same probes are
/// run before each application transaction commits and during startup diagnostics.
/// </summary>
internal static class AccessInvariantProbes
{
    public static IReadOnlyList<(string Name, string Sql)> Continuity { get; } =
    [
        ("CanonEntities.VariantGroupId", "SELECT COUNT(*) FROM [CanonEntities] AS c INNER JOIN [VariantGroups] AS v ON c.[VariantGroupId]=v.[Id] WHERE c.[ContinuityId]<>v.[ContinuityId] OR c.[EntityType]<>v.[EntityType]"),
        ("Locations.ParentLocationId", "SELECT COUNT(*) FROM ([Locations] AS d INNER JOIN [CanonEntities] AS dc ON d.[EntityId]=dc.[Id]) INNER JOIN ([Locations] AS p INNER JOIN [CanonEntities] AS pc ON p.[EntityId]=pc.[Id]) ON d.[ParentLocationId]=p.[EntityId] WHERE dc.[ContinuityId]<>pc.[ContinuityId]"),
        ("Characters.SpeciesId", "SELECT COUNT(*) FROM ([Characters] AS d INNER JOIN [CanonEntities] AS dc ON d.[EntityId]=dc.[Id]) INNER JOIN [CanonEntities] AS pc ON d.[SpeciesId]=pc.[Id] WHERE dc.[ContinuityId]<>pc.[ContinuityId]"),
        ("Characters.BirthLocationId", "SELECT COUNT(*) FROM ([Characters] AS d INNER JOIN [CanonEntities] AS dc ON d.[EntityId]=dc.[Id]) INNER JOIN ([Locations] AS p INNER JOIN [CanonEntities] AS pc ON p.[EntityId]=pc.[Id]) ON d.[BirthLocationId]=p.[EntityId] WHERE dc.[ContinuityId]<>pc.[ContinuityId]"),
        ("ProjectEntities", "SELECT COUNT(*) FROM ([ProjectEntities] AS x INNER JOIN [CanonEntities] AS p ON x.[ProjectId]=p.[Id]) INNER JOIN [CanonEntities] AS m ON x.[MemberEntityId]=m.[Id] WHERE p.[ContinuityId]<>m.[ContinuityId]"),
        ("EntityEvents.WorldEventId", "SELECT COUNT(*) FROM ([EntityEvents] AS x INNER JOIN [CanonEntities] AS e ON x.[EntityId]=e.[Id]) INNER JOIN [CanonEntities] AS w ON x.[WorldEventId]=w.[Id] WHERE e.[ContinuityId]<>w.[ContinuityId]"),
        ("EntityEventProjects", "SELECT COUNT(*) FROM (([EntityEventProjects] AS x INNER JOIN [EntityEvents] AS ev ON x.[EntityEventId]=ev.[Id]) INNER JOIN [CanonEntities] AS e ON ev.[EntityId]=e.[Id]) INNER JOIN [CanonEntities] AS p ON x.[ProjectId]=p.[Id] WHERE e.[ContinuityId]<>p.[ContinuityId]"),
        ("CharacterTemporalEffects.CharacterId", "SELECT COUNT(*) FROM [CharacterTemporalEffects] AS x INNER JOIN [CanonEntities] AS c ON x.[CharacterId]=c.[Id] WHERE x.[ContinuityId]<>c.[ContinuityId]"),
        ("CharacterTemporalEffects.WorldEventId", "SELECT COUNT(*) FROM [CharacterTemporalEffects] AS x INNER JOIN [CanonEntities] AS w ON x.[WorldEventId]=w.[Id] WHERE x.[ContinuityId]<>w.[ContinuityId]"),
        ("CharacterResidences", "SELECT COUNT(*) FROM ([CharacterResidences] AS x INNER JOIN [CanonEntities] AS c ON x.[CharacterId]=c.[Id]) INNER JOIN [CanonEntities] AS l ON x.[LocationId]=l.[Id] WHERE c.[ContinuityId]<>l.[ContinuityId]"),
        ("OrganizationMemberships", "SELECT COUNT(*) FROM ([OrganizationMemberships] AS x INNER JOIN [CanonEntities] AS o ON x.[OrganizationId]=o.[Id]) INNER JOIN [CanonEntities] AS c ON x.[CharacterId]=c.[Id] WHERE o.[ContinuityId]<>c.[ContinuityId]"),
        ("OrganizationLocations", "SELECT COUNT(*) FROM ([OrganizationLocations] AS x INNER JOIN [CanonEntities] AS o ON x.[OrganizationId]=o.[Id]) INNER JOIN [CanonEntities] AS l ON x.[LocationId]=l.[Id] WHERE o.[ContinuityId]<>l.[ContinuityId]"),
        ("CharacterRelationships", "SELECT COUNT(*) FROM ([CharacterRelationships] AS r INNER JOIN [CanonEntities] AS s ON r.[SourceCharacterId]=s.[Id]) INNER JOIN [CanonEntities] AS t ON r.[TargetCharacterId]=t.[Id] WHERE r.[ContinuityId]<>s.[ContinuityId] OR r.[ContinuityId]<>t.[ContinuityId]"),
        ("RelationshipParticipants", "SELECT COUNT(*) FROM ([RelationshipParticipants] AS p INNER JOIN [CharacterRelationships] AS r ON p.[RelationshipId]=r.[Id]) INNER JOIN [CanonEntities] AS c ON p.[CharacterId]=c.[Id] WHERE r.[ContinuityId]<>c.[ContinuityId]"),
        ("RelationshipEvents.WorldEventId", "SELECT COUNT(*) FROM ([RelationshipEvents] AS e INNER JOIN [CharacterRelationships] AS r ON e.[RelationshipId]=r.[Id]) INNER JOIN [CanonEntities] AS w ON e.[WorldEventId]=w.[Id] WHERE r.[ContinuityId]<>w.[ContinuityId]"),
        ("RelationshipEventProjects", "SELECT COUNT(*) FROM (([RelationshipEventProjects] AS x INNER JOIN [RelationshipEvents] AS e ON x.[RelationshipEventId]=e.[Id]) INNER JOIN [CharacterRelationships] AS r ON e.[RelationshipId]=r.[Id]) INNER JOIN [CanonEntities] AS p ON x.[ProjectId]=p.[Id] WHERE r.[ContinuityId]<>p.[ContinuityId]"),
        ("OwnershipPrincipals.CharacterId", "SELECT COUNT(*) FROM [OwnershipPrincipals] AS p INNER JOIN [CanonEntities] AS c ON p.[CharacterId]=c.[Id] WHERE p.[ContinuityId]<>c.[ContinuityId]"),
        ("OwnershipPrincipals.OrganizationId", "SELECT COUNT(*) FROM [OwnershipPrincipals] AS p INNER JOIN [CanonEntities] AS o ON p.[OrganizationId]=o.[Id] WHERE p.[ContinuityId]<>o.[ContinuityId]"),
        ("ObjectOwnershipOwners", "SELECT COUNT(*) FROM ([ObjectOwnershipOwners] AS x INNER JOIN [OwnershipPrincipals] AS p ON x.[PrincipalId]=p.[Id]) INNER JOIN ([ObjectOwnershipPeriods] AS q INNER JOIN [CanonEntities] AS o ON q.[ObjectId]=o.[Id]) ON x.[OwnershipPeriodId]=q.[Id] WHERE p.[ContinuityId]<>o.[ContinuityId]"),
        ("ObjectCustodyPeriods", "SELECT COUNT(*) FROM ([ObjectCustodyPeriods] AS x INNER JOIN [CanonEntities] AS o ON x.[ObjectId]=o.[Id]) INNER JOIN [OwnershipPrincipals] AS p ON x.[PrincipalId]=p.[Id] WHERE o.[ContinuityId]<>p.[ContinuityId]"),
        ("ObjectLocationPeriods", "SELECT COUNT(*) FROM ([ObjectLocationPeriods] AS x INNER JOIN [CanonEntities] AS o ON x.[ObjectId]=o.[Id]) INNER JOIN [CanonEntities] AS l ON x.[LocationId]=l.[Id] WHERE o.[ContinuityId]<>l.[ContinuityId]"),
        ("WorldEventParticipants", "SELECT COUNT(*) FROM ([WorldEventParticipants] AS x INNER JOIN [CanonEntities] AS w ON x.[WorldEventId]=w.[Id]) INNER JOIN [CanonEntities] AS p ON x.[ParticipantEntityId]=p.[Id] WHERE w.[ContinuityId]<>p.[ContinuityId]"),
        ("WorldEventLocations", "SELECT COUNT(*) FROM ([WorldEventLocations] AS x INNER JOIN [CanonEntities] AS w ON x.[WorldEventId]=w.[Id]) INNER JOIN [CanonEntities] AS l ON x.[LocationId]=l.[Id] WHERE w.[ContinuityId]<>l.[ContinuityId]"),
        ("ClaimEntities", "SELECT COUNT(*) FROM ([ClaimEntities] AS x INNER JOIN [Claims] AS c ON x.[ClaimId]=c.[Id]) INNER JOIN [CanonEntities] AS e ON x.[EntityId]=e.[Id] WHERE c.[ContinuityId]<>e.[ContinuityId]"),
        ("ClaimRelationships", "SELECT COUNT(*) FROM ([ClaimRelationships] AS x INNER JOIN [Claims] AS c ON x.[ClaimId]=c.[Id]) INNER JOIN [CharacterRelationships] AS r ON x.[RelationshipId]=r.[Id] WHERE c.[ContinuityId]<>r.[ContinuityId]"),
        ("ClaimNotes", "SELECT COUNT(*) FROM ([ClaimNotes] AS x INNER JOIN [Claims] AS c ON x.[ClaimId]=c.[Id]) INNER JOIN ([EntityNotes] AS n INNER JOIN [CanonEntities] AS e ON n.[EntityId]=e.[Id]) ON x.[NoteId]=n.[Id] WHERE c.[ContinuityId]<>e.[ContinuityId]")
    ];

    public static IReadOnlyList<(string Name, string Sql, string Detail)> Shapes { get; } =
    [
        ("ProjectEntities.MemberEntityId", "SELECT COUNT(*) FROM [ProjectEntities] AS x INNER JOIN [CanonEntities] AS m ON x.[MemberEntityId]=m.[Id] WHERE m.[EntityType]='Project'", "Project nesting is not supported by the flat project model."),
        ("EntityEvents.EntityId", "SELECT COUNT(*) FROM [EntityEvents] AS x INNER JOIN [CanonEntities] AS e ON x.[EntityId]=e.[Id] WHERE e.[EntityType] NOT IN ('Character','Location','Organization','Object','Project','Species')", "Entity-specific events may belong only to characters, locations, organizations, objects, projects, or species."),
        ("EntityEvents.Recurrence", "SELECT COUNT(*) FROM [EntityEvents] WHERE ([RecurrenceFrequency] IS NULL AND ([RecurrenceInterval] IS NOT NULL OR [RecurrenceUntil] IS NOT NULL)) OR ([RecurrenceFrequency] IS NOT NULL AND ([RecurrenceFrequency] NOT IN ('Daily','Weekly','Monthly','Yearly') OR [RecurrenceInterval] IS NULL OR [RecurrenceInterval]<1 OR [RecurrenceInterval]>10000 OR [EventKind]<>'ExactDate' OR [EventCalendarId]<>'Gregorian' OR [RecurrenceUntil]<[EventLowerBound]))", "Recurring events require an exact Gregorian day, a supported frequency, a positive interval, and an optional stop date on or after the first occurrence."),
        ("WorldEvents.Recurrence", "SELECT COUNT(*) FROM [WorldEvents] WHERE ([RecurrenceFrequency] IS NULL AND ([RecurrenceInterval] IS NOT NULL OR [RecurrenceUntil] IS NOT NULL)) OR ([RecurrenceFrequency] IS NOT NULL AND ([RecurrenceFrequency] NOT IN ('Daily','Weekly','Monthly','Yearly') OR [RecurrenceInterval] IS NULL OR [RecurrenceInterval]<1 OR [RecurrenceInterval]>10000 OR [EventKind]<>'ExactDate' OR [EventCalendarId]<>'Gregorian' OR [RecurrenceUntil]<[EventLowerBound]))", "Recurring events require an exact Gregorian day, a supported frequency, a positive interval, and an optional stop date on or after the first occurrence."),
        ("RelationshipEvents.Recurrence", "SELECT COUNT(*) FROM [RelationshipEvents] WHERE ([RecurrenceFrequency] IS NULL AND ([RecurrenceInterval] IS NOT NULL OR [RecurrenceUntil] IS NOT NULL)) OR ([RecurrenceFrequency] IS NOT NULL AND ([RecurrenceFrequency] NOT IN ('Daily','Weekly','Monthly','Yearly') OR [RecurrenceInterval] IS NULL OR [RecurrenceInterval]<1 OR [RecurrenceInterval]>10000 OR [EventKind]<>'ExactDate' OR [EventCalendarId]<>'Gregorian' OR [RecurrenceUntil]<[EventLowerBound]))", "Recurring events require an exact Gregorian day, a supported frequency, a positive interval, and an optional stop date on or after the first occurrence."),
        ("EntityEvents.RecurringBoundary", "SELECT COUNT(*) FROM [EntityEvents] WHERE [ProjectBoundary] IS NOT NULL AND [RecurrenceFrequency] IS NOT NULL", "Project boundaries cannot repeat."),
        ("EntityEvents.ProjectBoundary", "SELECT COUNT(*) FROM [EntityEvents] AS x INNER JOIN [CanonEntities] AS e ON x.[EntityId]=e.[Id] WHERE x.[ProjectBoundary] IS NOT NULL AND (e.[EntityType]<>'Project' OR x.[ProjectBoundary] NOT IN ('StoryBegins','StoryEnds'))", "Story boundaries require a project owner and a valid boundary role."),
        ("EntityEvents.DuplicateBoundary", "SELECT COUNT(*) FROM [EntityEvents] AS a INNER JOIN [EntityEvents] AS b ON a.[EntityId]=b.[EntityId] AND a.[ProjectBoundary]=b.[ProjectBoundary] WHERE a.[Id]<b.[Id] AND a.[IsDeleted]=False AND b.[IsDeleted]=False", "A project can have only one active event for each story boundary."),
        ("EntityEvents.BoundaryChronology", "SELECT COUNT(*) FROM [EntityEvents] AS a INNER JOIN [EntityEvents] AS b ON a.[EntityId]=b.[EntityId] WHERE a.[ProjectBoundary]='StoryBegins' AND b.[ProjectBoundary]='StoryEnds' AND a.[IsDeleted]=False AND b.[IsDeleted]=False AND (a.[EventCalendarId]<>b.[EventCalendarId] OR a.[EventLowerBound]>b.[EventUpperBound] OR (a.[EventLowerBound]=b.[EventUpperBound] AND NOT (a.[EventLowerInclusive]=True AND b.[EventUpperInclusive]=True)))", "Project story boundaries must use the same calendar and cannot end before they begin."),
        ("WorldEventParticipants.ParticipantEntityId", "SELECT COUNT(*) FROM [WorldEventParticipants] AS x INNER JOIN [CanonEntities] AS e ON x.[ParticipantEntityId]=e.[Id] WHERE e.[EntityType] NOT IN ('Character','Organization','Object')", "World-event participants may be characters, organizations, or objects; locations use WorldEventLocations."),
        ("Characters.BirthdayRecurring", "SELECT COUNT(*) FROM [Characters] WHERE [BirthdayRecurring]=True AND ([BirthKind]<>'ExactDate' OR [BirthCalendarId]<>'Gregorian' OR ([DeathKind]<>'Unknown' AND [DeathCalendarId]<>'Gregorian'))", "Repeating birthdays require an exact Gregorian birth date and a compatible death calendar."),
        ("Characters.BirthDeathChronology", "SELECT COUNT(*) FROM [Characters] WHERE [BirthLowerBound] IS NOT NULL AND [DeathUpperBound] IS NOT NULL AND ([DeathUpperBound]<[BirthLowerBound] OR ([DeathUpperBound]=[BirthLowerBound] AND NOT ([DeathUpperInclusive]=True AND [BirthLowerInclusive]=True)))", "A character's death is definitely earlier than their birth."),
        ("CharacterRelationships.CanonicalPair", "SELECT COUNT(*) FROM [CharacterRelationships] AS r INNER JOIN [RelationshipTypes] AS t ON r.[RelationshipTypeId]=t.[Id] WHERE t.[IsDirected]=False AND r.[SourceCharacterId]>r.[TargetCharacterId]", "Undirected relationship pairs must use ascending character IDs."),
        ("CharacterRelationships.DuplicatePeriod", "SELECT COUNT(*) FROM [CharacterRelationships] AS a INNER JOIN [CharacterRelationships] AS b ON a.[Id]<b.[Id] AND a.[SourceCharacterId]=b.[SourceCharacterId] AND a.[TargetCharacterId]=b.[TargetCharacterId] AND a.[RelationshipTypeId]=b.[RelationshipTypeId] AND a.[PeriodKind]=b.[PeriodKind] AND (a.[PeriodLowerBound]=b.[PeriodLowerBound] OR (a.[PeriodLowerBound] IS NULL AND b.[PeriodLowerBound] IS NULL)) AND (a.[PeriodUpperBound]=b.[PeriodUpperBound] OR (a.[PeriodUpperBound] IS NULL AND b.[PeriodUpperBound] IS NULL)) AND a.[PeriodLowerInclusive]=b.[PeriodLowerInclusive] AND a.[PeriodUpperInclusive]=b.[PeriodUpperInclusive] AND a.[PeriodCalendarId]=b.[PeriodCalendarId] WHERE a.[IsDeleted]=False AND b.[IsDeleted]=False", "Equivalent active relationship periods are duplicated."),
        ("RelationshipParticipants.Cardinality", "SELECT COUNT(*) FROM [CharacterRelationships] AS r WHERE r.[IsDeleted]=False AND (SELECT COUNT(*) FROM [RelationshipParticipants] AS p WHERE p.[RelationshipId]=r.[Id] AND p.[IsDeleted]=False) NOT BETWEEN 2 AND 100", "An active relationship must have between two and 100 active participants."),
        ("RelationshipParticipants.DirectedPair", "SELECT COUNT(*) FROM [CharacterRelationships] AS r INNER JOIN [RelationshipTypes] AS t ON r.[RelationshipTypeId]=t.[Id] WHERE r.[IsDeleted]=False AND t.[IsDirected]=True AND (SELECT COUNT(*) FROM [RelationshipParticipants] AS p WHERE p.[RelationshipId]=r.[Id] AND p.[IsDeleted]=False)>2", "Directed relationships cannot have more than two participants."),
        ("ClaimSources.SourceSnapshotId", "SELECT COUNT(*) FROM [ClaimSources] AS x INNER JOIN [SourceSnapshots] AS s ON x.[SourceSnapshotId]=s.[Id] WHERE x.[SourceId]<>s.[SourceId]", "A claim evidence snapshot must belong to its selected source."),
        ("ClaimSources.EvidenceRelation", "SELECT COUNT(*) FROM [ClaimSources] WHERE [EvidenceRelation] NOT IN ('Supports','Contradicts','Context')", "Claim evidence relation must be Supports, Contradicts, or Context."),
        ("WorldEventLocations.IsPrimary", "SELECT COUNT(*) FROM [WorldEventLocations] AS a INNER JOIN [WorldEventLocations] AS b ON a.[WorldEventId]=b.[WorldEventId] WHERE a.[Id]<b.[Id] AND a.[IsDeleted]=False AND b.[IsDeleted]=False AND a.[IsPrimary]=True AND b.[IsPrimary]=True", "A world event has more than one active primary location."),
        ("EntityImages.IsPrimary", "SELECT COUNT(*) FROM [EntityImages] AS a INNER JOIN [EntityImages] AS b ON a.[EntityId]=b.[EntityId] WHERE a.[Id]<b.[Id] AND a.[IsDeleted]=False AND b.[IsDeleted]=False AND a.[IsPrimary]=True AND b.[IsPrimary]=True", "An entity has more than one active primary image."),
        ("ImageRenditions.Completeness", "SELECT COUNT(*) FROM [EntityImages] AS i LEFT JOIN [ImageRenditions] AS r ON i.[Id]=r.[ImageId] WHERE i.[IsDeleted]=False GROUP BY i.[Id] HAVING COUNT(r.[RenditionKind])<>2", "Every active image must have exactly Thumbnail and Display renditions."),
        ("StoryImages.IsPrimary", "SELECT COUNT(*) FROM [StoryImages] AS a INNER JOIN [StoryImages] AS b ON a.[ContinuityId]=b.[ContinuityId] AND a.[OwnerKind]=b.[OwnerKind] AND (a.[OwnerKind]='Continuity' OR a.[RelationshipId]=b.[RelationshipId] OR a.[EntityEventId]=b.[EntityEventId] OR a.[RelationshipEventId]=b.[RelationshipEventId]) WHERE a.[Id]<b.[Id] AND a.[IsDeleted]=False AND b.[IsDeleted]=False AND a.[IsPrimary]=True AND b.[IsPrimary]=True", "A story record has more than one active primary image."),
        ("StoryImages.RelationshipContinuity", "SELECT COUNT(*) FROM [StoryImages] AS i INNER JOIN [CharacterRelationships] AS r ON i.[RelationshipId]=r.[Id] WHERE i.[OwnerKind]='Relationship' AND i.[ContinuityId]<>r.[ContinuityId]", "A relationship image is stored in a different continuity from its owner."),
        ("StoryImages.EntityEventContinuity", "SELECT COUNT(*) FROM ([StoryImages] AS i INNER JOIN [EntityEvents] AS e ON i.[EntityEventId]=e.[Id]) INNER JOIN [CanonEntities] AS c ON e.[EntityId]=c.[Id] WHERE i.[OwnerKind]='EntityEvent' AND i.[ContinuityId]<>c.[ContinuityId]", "An entity-event image is stored in a different continuity from its owner."),
        ("StoryImages.RelationshipEventContinuity", "SELECT COUNT(*) FROM ([StoryImages] AS i INNER JOIN [RelationshipEvents] AS e ON i.[RelationshipEventId]=e.[Id]) INNER JOIN [CharacterRelationships] AS r ON e.[RelationshipId]=r.[Id] WHERE i.[OwnerKind]='RelationshipEvent' AND i.[ContinuityId]<>r.[ContinuityId]", "A relationship-event image is stored in a different continuity from its owner."),
        ("StoryImageRenditions.Completeness", "SELECT COUNT(*) FROM [StoryImages] AS i LEFT JOIN [StoryImageRenditions] AS r ON i.[Id]=r.[ImageId] WHERE i.[IsDeleted]=False GROUP BY i.[Id] HAVING COUNT(r.[RenditionKind])<>2", "Every active story image must have exactly Thumbnail and Display renditions."),
        ("ImageContentVersions.EntityMissing", "SELECT COUNT(*) FROM [EntityImages] AS i WHERE NOT EXISTS (SELECT * FROM [ImageContentVersions] AS v WHERE v.[ImageId]=i.[Id] AND v.[ImageKind]='EntityImage')", "Every entity image needs a content revision mapping."),
        ("ImageContentVersions.StoryMissing", "SELECT COUNT(*) FROM [StoryImages] AS i WHERE NOT EXISTS (SELECT * FROM [ImageContentVersions] AS v WHERE v.[ImageId]=i.[Id] AND v.[ImageKind]='StoryImage')", "Every story image needs a content revision mapping."),
        ("ImageHistoricalContent.FutureRevision", "SELECT COUNT(*) FROM [ImageHistoricalContent] AS h INNER JOIN [ImageContentVersions] AS v ON h.[ImageKind]=v.[ImageKind] AND h.[ImageId]=v.[ImageId] WHERE h.[ContentRevision]>=[CurrentRevision]", "Historical image content must precede the current revision."),
        ("ObjectCustodyPeriods.CustodianState", "SELECT COUNT(*) FROM [ObjectCustodyPeriods] WHERE NOT (([CustodianState]='Known' AND [PrincipalId] IS NOT NULL) OR ([CustodianState] IN ('Unknown','Unowned') AND [PrincipalId] IS NULL))", "Custody state and principal are inconsistent."),
        ("OwnershipPrincipals.PrincipalKind", "SELECT COUNT(*) FROM [OwnershipPrincipals] WHERE NOT (([PrincipalKind]='Character' AND [CharacterId] IS NOT NULL AND [OrganizationId] IS NULL AND [Label] IS NULL) OR ([PrincipalKind]='Organization' AND [CharacterId] IS NULL AND [OrganizationId] IS NOT NULL AND [Label] IS NULL) OR ([PrincipalKind]='External' AND [CharacterId] IS NULL AND [OrganizationId] IS NULL AND [Label] IS NOT NULL AND Len(Trim([Label]))>0))", "Ownership principal kind and target are inconsistent.")
    ];
}
