import { build } from 'esbuild';
import { readFile, writeFile, mkdir, readdir, copyFile } from 'node:fs/promises';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = dirname(fileURLToPath(import.meta.url));
const output = resolve(root, '../../WritingVault.Web/wwwroot/vendor/markdown');
await mkdir(output, { recursive: true });
await copyFile(resolve(root, '../../docs/MARKDOWN.md'), resolve(output, '../../markdown-help.md'));
for (const [entry, globalName] of [['vendor', 'WritingVaultMarkdownDeps'], ['mermaid', 'WritingVaultMermaid']]) {
  await build({ absWorkingDir: root, entryPoints: [`${entry}.mjs`],
    outfile: join(output, `${entry}.js`), bundle: true, minify: true,
    platform: 'browser', format: 'iife', globalName, target: ['chrome120'],
    legalComments: 'linked', logLevel: 'info' });
}
await copyFile(join(root, 'node_modules/katex/dist/katex.min.css'), join(output, 'katex.css'));
await mkdir(join(output, 'fonts'), { recursive: true });
for (const name of (await readdir(join(root, 'node_modules/katex/dist/fonts'))).sort()) {
  await copyFile(join(root, 'node_modules/katex/dist/fonts', name), join(output, 'fonts', name));
}

// Preserve full licenses for installed runtime packages, including dependencies
// whose notices are not retained by a minifier. No network is needed to build.
const lock = JSON.parse(await readFile(join(root, 'package-lock.json'), 'utf8'));
const notices = ['# Markdown third-party notices\n\nGenerated by tools/markdown/build.mjs.\n'];
for (const [path, metadata] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b))) {
  if (!path || metadata.dev || metadata.optional) continue;
  const directory = join(root, path);
  const pkg = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
  notices.push(`\n## ${pkg.name} ${pkg.version}\nLicense: ${typeof pkg.license === 'string' ? pkg.license : JSON.stringify(pkg.license)}\n`);
  for (const name of (await readdir(directory)).filter(name => /^(licen[cs]e|copying|notice)(\.|$)/i.test(name)).sort()) {
    const text = await readFile(join(directory, name), 'utf8').catch(() => null);
    if (text) notices.push(`\n${text}\n`);
  }
}
await writeFile(join(output, 'THIRD-PARTY-NOTICES.txt'), notices.join(''));
const files = [];
async function inventory(directory) {
  for (const item of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
    const path = join(directory, item.name);
    if (item.isDirectory()) await inventory(path);
    else if (item.name !== 'manifest.json') {
      const bytes = await readFile(path);
      files.push({ path: relative(output, path).replaceAll('\\', '/'), bytes: bytes.length,
        sha256: createHash('sha256').update(bytes).digest('hex') });
    }
  }
}
await inventory(output);
await writeFile(join(output, 'manifest.json'), JSON.stringify({
  packageLockSha256: createHash('sha256').update(await readFile(join(root, 'package-lock.json'))).digest('hex'),
  packages: Object.fromEntries(Object.entries(lock.packages).filter(([path, value]) => path && !value.dev && !value.optional)
    .map(([path, value]) => [path, value.version])), files
}, null, 2) + '\n');
